github ejercicio
Sophia347/apprenticeshipSofia pull request #13
Opened 2023-03-06 17:09 UTC by Sophia347

2023-03-06 17:57 UTC, anamariagp2010 commented on node_scripting/node_tool.js
>    const octokit = new Octokit({ auth: authentication });
Esta constante la puedes poner bajo la línea 4, para que no tengas que crearla dentro de cada función, sino que sea una variable global

2023-03-06 17:58 UTC, anamariagp2010 commented on node_scripting/node_tool.js
> +async function enlistarColumnas(projects_ids) {
ya que "projects_ids" es un array de objetos donde no solo hay ids sino también nombres, puedes cambiarle el nombre por "projects"

2023-03-06 17:59 UTC, anamariagp2010 commented on node_scripting/node_tool.js
> +  const octokit = new Octokit({ auth: authentication });
Esta constante la puedes eliminar porque la vas a poner global

2023-03-06 18:00 UTC, anamariagp2010 commented on node_scripting/node_tool.js
> +    const columnsUrl = "/columns";
estas 2 constantes las puedes crear antes del while

2023-03-06 18:02 UTC, anamariagp2010 commented on node_scripting/node_tool.js
> +  let resultado = [];
A esta variable le puedes cambiar el nombre por "dataTmp"

2023-03-06 18:03 UTC, anamariagp2010 commented on node_scripting/node_tool.js
> +  let columnsIdsFinal = [];
Esta variable se podría llamar "columns_result"

2023-03-06 18:03 UTC, anamariagp2010 commented on node_scripting/node_tool.js
> +async function enlistarCards(columns_ids) {
ya que "columns_ids" es un array de objetos donde no solo hay ids sino también nombres, puedes cambiarle el nombre por "columns"

2023-03-06 18:05 UTC, anamariagp2010 commented on node_scripting/node_tool.js
> +          columns_name: columns_ids[i].column_name,
cámbiale el "columns_name:" por "column_name:", ya que es el nombre de sólo 1 columna

2023-03-06 18:05 UTC, anamariagp2010 commented on node_scripting/node_tool.js
> +async function getCardsNames(cards_ids) {
ya que "cards_ids" es un array de objetos donde no solo hay ids sino también nombres, puedes cambiarle el nombre por "cards"

2023-03-06 18:06 UTC, anamariagp2010 commented on node_scripting/node_tool.js
> +  const octokit = new Octokit({ auth: authentication });
Este también eliminalo

2023-03-06 18:07 UTC, anamariagp2010 commented on node_scripting/node_tool.js
> +            columns_name: card.columns_name,
cambia esta línea por: "column_name: card.column_name,"

2023-03-06 18:08 UTC, anamariagp2010 commented on node_scripting/node_tool.js
> +    const projects_ids = await enlistarProyectos(repo);
cambia el nombre por solo "projects"

2023-03-06 18:08 UTC, anamariagp2010 commented on node_scripting/node_tool.js
> +    const columns_ids = await enlistarColumnas(projects_ids);
cambia el nombre por solo "columns"

2023-03-06 18:08 UTC, anamariagp2010 commented on node_scripting/node_tool.js
> +    const cards_ids = await enlistarCards(columns_ids);
cambia el nombre por solo "cards"

2023-03-06 18:11 UTC, anamariagp2010 commented on node_scripting/node_tool.js
> +    console.log("card_names:", card_names);
console.log("Información de los proyectos del repositorio: ", repo, "\n", projects_info);

2023-03-06 18:12 UTC, anamariagp2010 requested changes
Te dejé algunos comentarios menores :)

2023-03-06 21:01 UTC, Sophia347 commented on node_scripting/node_tool.js
> +  let resultado = [];
resultado por dataTmp? en todas las funciones ?m

2023-03-07 18:46 UTC, anamariagp2010 commented on node_scripting/node_tool.js
>    const octokit = new Octokit({ auth: authentication });
@Sophia347 Recuerda eliminar este const

2023-03-07 18:46 UTC, anamariagp2010 requested changes
Sólo 1 cambio mas

2023-03-08 17:08 UTC, anamariagp2010 approved these changes
Looks great! Congratulations Sofia :D

2023-03-08 17:08 UTC, merged